node {
  checkout scm

  docker.image('maven:3-jdk-11').inside('-u root -v /$HOME/.m2/:/root/.m2') {
    stage('Build') {
       sh 'mvn -B -DskipTests clean package'
     }

     stage('Test') {
       sh 'mvn test'
     }

     stage('Print'){
         sh 'ls'
         sh 'pwd'
     }
  }


}