node {
  checkout scm

  docker.image('node:10-alpine').withRun('-v /$HOME/.m2/:/root/.m2').inside {
    stage('Build') {
       sh 'mvn -B -DskipTests clean package'
     }

     stage('Test') {
       sh 'mvn test'
     }
  }
}