apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  labels:
    app: APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APP_NAME
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
        - name: APP_NAME
          image: IMAGE_NAME
          volumeMounts:
            - mountPath: /dev/gpiomem
              name: pi-gpio
          securityContext:
            privileged: true
      volumes:
        - name: pi-gpio
          hostPath:
            path: /dev/gpiomem
      restartPolicy: Always